name: rumos_bank_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9.21
  - fastapi
  - uvicorn
  - alembic
  - sqlalchemy
  - requests
  - numpy==2.0.2  # Versão estável
  - pandas
  - scipy
  - scikit-learn
  - mlflow=2.20.4
  - flask
  - gunicorn
  - pip
  - psutil>=5.8  # Atualizado para evitar problemas
  - pip:
      - protobuf
      - graphene
      - graphql-core
      - graphql-relay
      - opentelemetry-api
      - opentelemetry-sdk
