name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar Docker Buildx (opcional, mas recomendado para compatibilidade com multiplataformas)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 3: (Opcional) Login no Docker Hub
      # Caso precise de acesso a imagens privadas no Docker Hub ou outro registro.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dinisvictor
          password: dckr_pat_SlXFGzi2XKNkO-Q0tZiyY_0i8nQ

      # Passo 4: Rodar o docker-compose
      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      # Passo 5: Verificar se os contêineres estão rodando
      - name: Verify Docker Containers are Running
        run: |
          docker ps

      # Passo 6: Parar os contêineres após o teste
      - name: Stop Docker Containers
        run: |
          docker-compose down
        
      - name: Enviar imagem mlflow para o repositório do GitHub
        run: docker push ghcr.io/mlflow/mlflow

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/dinisvictor/rumos_bank_service:latest

      - name: Enviar imagem ui para o repositório do GitHub
        run: docker push ghcr.io/dinisvictor/rumos_bank_ui:latest
