name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Configurar Docker Buildx (opcional, mas recomendado para compatibilidade com multiplataformas)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 4: Rodar o docker-compose
      - name: Run Docker Compose
        run: docker compose up -d

      # # Cria o ambiente conda para rodar os testes
      # - name: Criar ambiente para executar testes com o conda
      #   uses: conda-incubator/setup-miniconda@v2
      #   with:
      #     environment-file: conda.yaml
      #     activate-environment: rumos_bank_env

      # # Rodar os testes diretamente na imagem do Docker (adicionando o comando)
      # - name: Run tests inside Docker
      #   run: docker exec rumos-bank-lending-service conda run -n rumos_bank_env pytest tests/

       # Esperar a API estar pronta
      - name: Aguardar serviço da API iniciar (porta 5002)
        run: |
          echo "⏳ Aguardando o serviço iniciar na porta 5002..."
          until curl -s http://localhost:5002/docs > /dev/null; do
            echo "Aguardando API no localhost:5002..."
            sleep 3
          done
          echo "API está ativa!"

        # Rodar testes de serviço
      - name: Testes - Service
        run: |
          docker exec rumos-bank-lending-service conda run -n rumos_bank_env pytest tests/test_service.py

      # Rodar testes de modelo
      - name: Testes - Model
        run: |
          docker exec rumos-bank-lending-service conda run -n rumos_bank_env pytest tests/test_model.py

        
  
      # - name: Instalar pytest no ambiente Conda
      #   run: |
      #     conda activate rumos_bank_env
      
      
      # # roda dos testes
      # - name: Executar testes
      #   run: conda run --no-capture-output -n rumos_bank_env pytest

      # Passo 3: (Opcional) Login no Docker Hub
      # Caso precise de acesso a imagens privadas no Docker Hub ou outro registro.
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: dinisvictor
          password: dckr_pat_SlXFGzi2XKNkO-Q0tZiyY_0i8nQ

      # # Passo 4: Rodar o docker-compose
      # - name: Run Docker Compose
      #   run: |
      #     docker-compose up -d

      # Passo 5:
      - name: Verify Docker Containers are Running
        run: |
          docker ps

      # Passo 6:
      - name: Stop Docker Containers
        run: |
          docker-compose down
        
      - name: Enviar imagem mlflow para o repositório do GitHub
        run: docker push ghcr.io/mlflow/mlflow:latest

      - name: Enviar imagem serviço para o repositório do GitHub
        run: docker push ghcr.io/dinisvictor/rumos_bank_service:latest

      - name: Enviar imagem ui para o repositório do GitHub
        run: docker push ghcr.io/dinisvictor/rumos_bank_ui:latest
