name: Build and Run Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        platform: [linux/arm64]

    steps:
      # Suporte multiplataforma (arm64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
          
      # Step 5: Run Docker Compose
      - name: Run Docker Compose
        run: docker compose up --build -d

      # Step 6: Check container logs
      - name: Check container logs (debug)
        run: docker logs rumos-bank-lending-service || true

      - name: Check mlflow-tracking mlruns/
        run: docker exec mlflow-tracking ls -l mlruns/

      - name: Check mlflow-tracking mlruns/models
        run: docker exec mlflow-tracking ls -l mlruns/models

      # Step 7: Wait for API to be ready
      - name: Wait for API on localhost:5002
        run: |
          echo "Waiting for API on localhost:5002..."
          for i in {1..30}; do
            if curl --silent http://localhost:5002/docs > /dev/null; then
              echo "API is ready!"
              exit 0
            fi
            echo "⏳ Still waiting..."
            sleep 3
          done
          echo "Timeout waiting for API!"
          docker logs rumos-bank-lending-service || true
          exit 1

      # Step 8: Show service logs
      - name: Show logs before tests
        run: docker logs rumos-bank-lending-service

      # Step 9: Run service tests
      - name: Run Service Tests
        run: |
          docker exec rumos-bank-lending-service conda run -n rumos_bank_env pytest

     # Step 11: Push images to GitHub Container Registry
      - name: Push service image
        run: docker push ghcr.io/dinisvictor/rumos_bank_service:latest

      - name: Push UI image
        run: docker push ghcr.io/dinisvictor/rumos_bank_ui:latest

      # Step 12: Tear down containers
      - name: Stop Docker Containers
        run: docker compose down

      
